/*
 * Created on 2021-01-24 ( Time 21:50:13 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.palmafrique.palm.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "agent"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="agent" )
public class Agent implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nom", nullable=false, length=255)
    private String     nom          ;

    @Column(name="prenom", nullable=false, length=255)
    private String     prenom       ;

    @Column(name="sexe", nullable=false, length=1)
    private String     sexe         ;

    @Column(name="nombre_heure", length=250)
    private String     nombreHeure  ;

    @Column(name="telephone", nullable=false, length=255)
    private String     telephone    ;

    @Column(name="age", nullable=false, length=250)
    private String     age          ;

    @Column(name="username", nullable=false, length=255)
    private String     username     ;

    @Column(name="password", nullable=false, length=255)
    private String     password     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

	// "siteId" (column "site_id") is not defined by itself because used as FK in a link 
	// "directionId" (column "direction_id") is not defined by itself because used as FK in a link 
	// "serviceId" (column "service_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="service_id", referencedColumnName="id")
    private Service service     ;
    @ManyToOne
    @JoinColumn(name="site_id", referencedColumnName="id")
    private Site site        ;
    @ManyToOne
    @JoinColumn(name="direction_id", referencedColumnName="id")
    private Direction direction   ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Agent() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
