/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package ci.palmafrique.palm.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// ABSENCE
	VIEW_ABSENCE("VIEW_ABSENCE"),	
	CREATE_ABSENCE("CREATE_ABSENCE"),
	UPDATE_ABSENCE("UPDATE_ABSENCE"),
	DELETE_ABSENCE("DELETE_ABSENCE"),
	// ADMIN
	VIEW_ADMIN("VIEW_ADMIN"),	
	CREATE_ADMIN("CREATE_ADMIN"),
	UPDATE_ADMIN("UPDATE_ADMIN"),
	DELETE_ADMIN("DELETE_ADMIN"),
	// AGENT
	VIEW_AGENT("VIEW_AGENT"),	
	CREATE_AGENT("CREATE_AGENT"),
	UPDATE_AGENT("UPDATE_AGENT"),
	DELETE_AGENT("DELETE_AGENT"),
	// DIRECTION
	VIEW_DIRECTION("VIEW_DIRECTION"),	
	CREATE_DIRECTION("CREATE_DIRECTION"),
	UPDATE_DIRECTION("UPDATE_DIRECTION"),
	DELETE_DIRECTION("DELETE_DIRECTION"),
	// MEDECIN
	VIEW_MEDECIN("VIEW_MEDECIN"),	
	CREATE_MEDECIN("CREATE_MEDECIN"),
	UPDATE_MEDECIN("UPDATE_MEDECIN"),
	DELETE_MEDECIN("DELETE_MEDECIN"),
	// SERVICE
	VIEW_SERVICE("VIEW_SERVICE"),	
	CREATE_SERVICE("CREATE_SERVICE"),
	UPDATE_SERVICE("UPDATE_SERVICE"),
	DELETE_SERVICE("DELETE_SERVICE"),
	// SITE
	VIEW_SITE("VIEW_SITE"),	
	CREATE_SITE("CREATE_SITE"),
	UPDATE_SITE("UPDATE_SITE"),
	DELETE_SITE("DELETE_SITE"),
	// TYPEABSENCE
	VIEW_TYPEABSENCE("VIEW_TYPEABSENCE"),	
	CREATE_TYPEABSENCE("CREATE_TYPEABSENCE"),
	UPDATE_TYPEABSENCE("UPDATE_TYPEABSENCE"),
	DELETE_TYPEABSENCE("DELETE_TYPEABSENCE");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
